#!/bin/sh

set -e

npm install -g typescript typescript-language-server
npm install -g svelte-language-server
npm install -g pyright

GOBIN="/usr/local/bin" go install golang.org/x/tools/gopls@latest
