#!/bin/sh

set -e

tmp_dir=$(mktemp -d)
trap 'rm -rf $tmp_dir' EXIT

npm install -g typescript typescript-language-server
npm install -g svelte-language-server
npm install -g pyright

GOBIN="/usr/local/bin" go install golang.org/x/tools/gopls@latest

cd "$tmp_dir"

tarball_name="zls.tar.xz"
curl -fLo "$tarball_name" https://github.com/zigtools/zls/releases/latest/download/zls-x86_64-linux.tar.xz
tar -xf "$tarball_name"
mv ./zls /usr/local/bin

tarball_name="nvim.tar.gz"
curl -fLo "$tarball_name" https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz
tar -xz --no-same-owner --no-same-permissions -f "$tarball_name"
cd nvim-linux-x86_64
cp -r bin lib share /usr/
